apiVersion: v1
kind: Namespace
metadata:
  name: managedns
---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    argocd.argoproj.io/managed-by: argocd
